[package]
name = "lmprs2"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.5"
bitcoin_hashes = "0.16.0"
hashbrown = "0.15.2"
lightning = "0.1.1"
possiblyrandom = "0.2.0"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(fuzzing)'] }
